dist: xenial
language: bash
services:
    - docker
before_install:
  - echo $TRAVIS_BUILD_DIR
  - docker run --rm hello-world
before_script:
  - docker-compose up -d database
  - ./support/wait-for-database.sh
script:  
  - docker-compose run --rm tests
  
