dist: xenial
language: bash
services:
    - docker
before_install:
  - echo $TRAVIS_BUILD_DIR
  - docker -v
  - docker run --rm hello-world
before_script:
  - docker-compose up -d database
  - ./support/wait-for-database.sh
script:  
  - docker-compose run --rm -w /home/dev node -c "ls -la"
  - docker-compose run --rm -w /home/dev node -c "chown -R dev:dev /home/dev/app"
  - docker-compose run --rm -w /home/dev node -c "ls -la"
  - docker-compose run --rm -w /home/dev/app node -c "ls -la"
  - docker-compose run --rm -w /home/dev/app node -c "npm install"
  
