dist: xenial
language: bash
services:
    - docker
before_install:
  - echo $TRAVIS_BUILD_DIR
  - docker -v
  - docker run --rm hello-world
before_script:
  - docker-compose up -d database
  - ./support/wait-for-database.sh
  - docker build -t node:tests .
script:  
  - docker-compose run --rm tests -c "ls -la"
  - docker-compose run --rm tests -c "npm install"
  
