version: '3.4'

services:

  data:
    image: postgres:12
    container_name: postgres
    ports:
      - 2345:5432
    environment:
      - POSTGRES_DB=data
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      
  code:
    image: ericminio/node
    container_node: node
    
