version: '3.7'

services:

  database:
    image: postgres:12
    container_name: postgres
    ports:
      - 2345:5432
    environment:
      - POSTGRES_DB=data
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      
  ci:
    build: 
      context: .
      dockerfile: ./support/Dockerfile
    image: node:tests
    container_name: tests
    environment: 
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=data
      - PGUSER=dev
      - PGPASSWORD=dev
    command: ./support/run-tests.sh

  dev:
    image: ericminio/node
    container_name: node
    environment: 
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=data
      - PGUSER=dev
      - PGPASSWORD=dev
    volumes:
      - ./app:/home/dev/app
    working_dir: /home/dev/app
