version: '3.7'

services:

  database:
    image: postgres:12
    container_name: postgres
    ports:
      - 2345:5432
    environment:
      - POSTGRES_DB=data
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      
  tests:
    image: node:tests
    container_name: tests

  node:
    image: ericminio/node
    container_name: node
    volumes:
      - ./app:/home/dev/app

  install:
    image: ericminio/node
    container_name: install
    user: dev
    working_dir: /home/dev/app
    volumes:
      - ./app:/home/dev/app
    command: "npm install"
