version: '3.7'

services:

  database:
    image: postgres:12
    container_name: postgres
    ports:
      - 2345:5432
    environment:
      - POSTGRES_DB=data
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      
  tests:
    build: 
      context: .
      dockerfile: ./support/Dockerfile
    image: node:tests
    container_name: tests
    command: ./support/run-tests.sh

  node:
    image: ericminio/node
    container_name: node
    volumes:
      - ./app:/home/dev/app
