version: '3.4'

services:

  database:
    image: postgres:12
    container_name: postgres
    ports:
      - 2345:5432
    environment:
      - POSTGRES_DB=data
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      
  tests:
    image: ericminio/node
    container_name: tests
    volumes:
      - .:/usr/local/src
    command: /usr/local/src/support/run-tests.sh

  node:
    image: ericminio/node
    container_name: node
    volumes:
      - .:/usr/local/src
