version: '3.4'

services:

  database:
    image: postgres:12
    container_name: postgres
    ports:
      - 2345:5432
    environment:
      - POSTGRES_DB=data
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      
  node:
    image: node:app
    container_name: node
    volumes:
      - ./app:/home/dev/app
