version: '3.4'

services:

  database:
    image: postgres:12
    container_name: postgres
    ports:
      - 2345:5432
    environment:
      - POSTGRES_DB=data
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      
  tests:
    image: ericminio/node
    container_name: node
    volumes:
      - .:/tmp
    command: -c "/tmp/support/run-tests.sh"
      
